rvm:
- 2.0.0
- 2.1
- 2.2

sudo: true

bundler_args: --without='vagrant'

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/fix-travis-201601-2/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake integration:docker

after_failure: cat docker_daemon.log
